### ISSUE TITLE
Cannot write two records if only their date differ

### ISSUE THREAD

**Issue by davidlandry93** [meteokid/python-rpn#25]
When I write two records in sequence, and these records have the same metadata except for the date, the second write overwrites the first one.

The assert fails on ppp2 with 2.1.b3

```python

import os
import numpy as np
import rpnpy.librmn.all as rmn

TARGET_FILE = '/tmp/test.fst'

if __name__ == '__main__':
    if os.path.isfile(TARGET_FILE):
        os.unlink(TARGET_FILE)

    phony_data = np.zeros((10,10,1), order='FORTRAN')

    grid = rmn.encodeGrid({
        'grtyp': 'L',
        'ni': phony_data.shape[0],
        'nj': phony_data.shape[1],
        'lat0': 0.0,
        'lon0': 0.0,
        'dlat': 1.0,
        'dlon': 1.0,
    })

    deet = 3600
    npas = 2
    record = grid
    record.update({
        'd': phony_data,
        'etiket': 'TEST',
        'nomvar': 'XX',
        'datev': rmn.newdate(rmn.NEWDATE_PRINT2STAMP, 20180302, 20000000),
        'dateo': rmn.newdate(rmn.NEWDATE_PRINT2STAMP, 20180302, 18000000),
        'deet': deet,
        'npas': npas,
    })

    target_fst = rmn.fstopenall(TARGET_FILE, rmn.FST_RW)
    rmn.fstecr(target_fst, record)

    record['datev'] = rmn.newdate(rmn.NEWDATE_PRINT2STAMP, 20190302, 20000000)
    record['dateo'] = rmn.newdate(rmn.NEWDATE_PRINT2STAMP, 20190302, 18000000)
    rmn.fstecr(target_fst, record)

    n_records = rmn.fstnbr(target_fst)
    rmn.fstcloseall(target_fst)

    assert(n_records == 2)
```

**Comment by meteokid** [comment]
Python-RPN is mainly a python interface to C/Fortran functions in librmn.  
As far as I can understand, this is an issue of librmn, not Python-RPN.  
_I might be wrong. If that is the case, please post more detail and re-open this issue._

Unfortunately the re-write (overwrite) option of fstecr (the one in librmn called by python-rpn) does not consider all of the record metadata.  
Unfortunately also the librmn maintainers told us they wont change this behaviour since it would render it not "backward compatible". This could have adverse effects on operational products.

I suppose Python-RPN could hack the `fstecr` function and double check if a record has the same metadata whenever the `rewrite` flag is on (which is the default).  
Lets put this as a feature request then! rewrite would have 2 modes then: False, True(librmn's way) and and new strict mode.

In the mean time you could specify the `rewrite=False` option to `fstecr` in your script.

**Comment by davidlandry93** [comment]
Thanks!
